name: sdrf_convert
channels:
  # list used channels to make sure it works with micromamba
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.12
  - setuptools
  - pip
  - xtandem
  - pip:
    - -e .[dev]
