[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "sdrf_convert"
version = "0.0.1"
requires-python = ">=3.11"

dependencies = [
    "pandas >= 2, < 2.1.0",
    "pyteomics >= 4.6, < 5",
    "lxml >= 4.9.3, < 5"
]


[project.optional-dependencies]
dev = [
    "pylint"
]


