[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "sdrf_convert"
version = "0.0.1"
requires-python = ">=3.11"

dependencies = [
    "pandas ~= 2.0",
    "pyteomics ~= 4.6",
    "lxml ~= 4.9.3",
    "sqlalchemy ~= 2.0",
]


[project.optional-dependencies]
dev = [
    "pylint"
]


